version: '2.1'
executors:
  php7-2:
    docker:
      - image: php:7.2-alpine
  php7-3:
    docker:
      - image: php:7.3-alpine
  php7-4:
    docker:
      - image: php:7.4-alpine

jobs:
  phpunit:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install alpine requirements for checkout
          command: apk add git openssh-client curl libzip-dev zip && docker-php-ext-install zip
      - run:
          name: composer
          command: |
            if [[ ! -f vendor/autoload.php ]]; then
                curl https://getcomposer.org/composer-stable.phar --location --silent  --output /usr/bin/composer; \
                chmod +x /usr/bin/composer; \
                composer install --no-progress --no-interaction; \
            fi
      - run:
          name: phpunit
          command: vendor/bin/phpunit --testdox

workflows:
  all-tests:
    jobs:
      - phpunit:
          matrix:
            parameters:
              executor: [php7-2, php7-3, php7-4]
